OBJS                             += aarch64/audio_convert_init.o    \
                                    aarch64/resample_init.o         \

NEON-OBJS                        += aarch64/audio_convert_neon.o    \
                                    aarch64/resample_neon.o         \
